name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        sed -i -e "s,_ \"github.com/mattn/go-oci8\",,g" web/server.go
        sed -i -e "s,_ \"gopkg.in/rana/ora.v4\",,g" web/server.go
        mkdir -p $GOPATH/src/github.com/vkuznet
        cp -r ../dbs2go $GOPATH/src/github.com/vkuznet
        make

    - name: Test
      run: |
        sed -i -e "s,_ \"github.com/mattn/go-oci8\",,g" web/server.go
        sed -i -e "s,_ \"gopkg.in/rana/ora.v4\",,g" web/server.go
        mkdir -p $GOPATH/src/github.com/vkuznet
        cp -r ../dbs2go $GOPATH/src/github.com/vkuznet
        make test
